### ISSUE TITLE
Repo and Live Site not in Synch

### ISSUE THREAD

**Issue by ghost** [meteor/tutorials#100]
This live document:

https://www.meteor.com/tutorials/angular/creating-an-app

Where is it located in the repo? I've located it here:

https://github.com/meteor/tutorials/blob/master/content/angular/step01.md

But it seems to be not the same.

**Comment by abernix** [comment]
That should be the correct file for that page, but if you read the [`README.md`](https://github.com/meteor/tutorials/blob/master/README.md) of the project, you'll see that the templates are generated and you'd need to run `./scripts/process-repo.rb blaze` if you've changed a branches tutorial details.

That being said, this `templates` repo is a submodule of the main Meteor website (not publicly modifiable), but you can use the [Tutorial Viewer](https://github.com/meteor/tutorial-viewer) app to test more complicated changes (though most basic text changes are okay to submit PRs for without the full process of running the tutorial viewer).  The actual style may not be identical, but it's a suitable test scenario.

Thanks for trying to make a contribution to the tutorials!

**Comment by ghost** [comment]
@abernix, you don't help me. I don't understand your elaborations (just wanted to edit one file, its **one** click with other projects).

Can you please reopen the issue (it's generally not the best thing to decide for a user when the issues he raised is solved).

The files I mentioned are out of synch, just look at them.

**Comment by abernix** [comment]
I'm sorry, you're correct.  The files do actually look different as well, which is what I thought you were referring to.  I'll reopen this and look into why they are actually not updated at the moment.

**Comment by abernix** [comment]
Turns out that file itself is no longer used and has been replaced with a ["shared" template](https://github.com/meteor/tutorials/blob/master/content/shared/step01.md) (since the steps are the same for Angular, Blaze and React).  This was the original intention of https://github.com/meteor/tutorials/commit/cd21922f33b353c4111298c9bd12eb8383b9fb7c but it looks like it only affected the React and Blaze tutorials originally.

Thanks!  (I am closing this, but still happy to reopen if you think it's still broken).

**Comment by ghost** [comment]
@abernix, the "in-synch" issue is fixed, so it's ok to close this. I try now to find a way to suggest changes (although they are big, and it's difficult, but I'll find a way)

**Comment by abernix** [comment]
@lazaridis-com Before you take the time to make big, difficult changes, you should probably open specific, manageable issue tasks that can be discussed first so you don't spend time working on something that might be overly complicated to change.  I'll forewarn you that many of the tutorial steps are tied closely to _actual_ commits in the `todo` repos (linked in on the README), and the tutorials often reflect the way that the Meteor tool itself works (often times for very important reasons).  Please do suggest improvements to the tutorial as necessary, but keep in mind that the actual reason they are done or documented that way is because of a design choice made in another repository (the tool/docs/packages themselves, for example).

If you find actual issues in [the Meteor Docs](https://docs.meteor.com/) or the [Meteor Guide](https://guide.meteor.com/), those might be good places to make contributions too (and the edits are much easier).

**Comment by ghost** [comment]
@abernix, I understand your elaborations, thank you for providing them.

For now, it looks that the best way would be to provide a Quick Start. You can then decide if you want to place it on the website, or not. I think its missing. Its the thing that you allow me to send a normal grade developer to your site, telling him: "Get Meteor, bring a blog live within 2 hours".

A 2nd step would be to provide a Tutorial, written independently from the existent one.

(In parallel, the existent 3-ui-tutorial could be improved by applying smaller changes, which affect mostly "reduce information" or "provide information at a later point" )

The most important thing is that you are aware that something has to be done.

Thanks again for your elaborations.
