### ISSUE TITLE
What's the Purpose of hideCompleted() in Simple-Todos?

### ISSUE THREAD

**Issue by mikeborozdin** [meteor/tutorials#13]
The Simple-Todos tutorial features `Session` in Step 8. On that page, there's a function called `hideCompleted()` - its purpose is not entirely clear.

``` js
hideCompleted: function () {
  return Session.get("hideCompleted");
}
```

Which is used in the template:

``` js
<input type="checkbox" checked="{{hideCompleted}}" />
```

There doesn't seem to be any need in it. A checkbox becomes checked when a user presses on it. And if you refresh the page, the contents of the `Session` object will be gone anyway.

Having that function and using it in the template makes it a confusing tutorial, as it has things which are not necessary.

**Comment by Hungle123** [comment]
adad

**Comment by stubailo** [comment]
If you edit your code and there is a hot code push, the contents of session will be maintained. If we didn't update the checkbox from session, it would then be out of sync.

Either way, it makes sense to drive the checkbox from a model because you could easily add some other code that sets or unsets that value, and you would want the checkbox to update. Perhaps it would be clearer if it was a button rather than an HTML checkbox.
