### ISSUE TITLE
Meteor Create Hangs (macOS High Sierra)

### ISSUE THREAD

**Issue by christopherholmes** [meteor/tutorials#163]
Hi, 

I've just come across a little problem with Meteor 1.6 when first creating a new app. 

The command hangs at "installing npm dependencies"

Seems to be struggling install babel-runtime. I can cancel the create, install babel manually with "meteor npm install --save babel-runtime" and the app will start successfully. Meteor reports all other packages up to date. 

Is this already a known issue?

**Comment by abernix** [comment]
It's best to open this on the [main Meteor repository](https://github.com/meteor/meteor/issues), rather than on the Tutorials repository.  It might be helpful if you ran `meteor` with `--verbose` or the `METEOR_DEBUG=log` environment variable set and provided that output in the new issue that you open, in order to help debug.  Please also specify what operating system you're using!  Thanks!
