### ISSUE TITLE
couldnt run the meteor todos, an  error popped up and im running on windows

### ISSUE THREAD

**Issue by chunmatt** [meteor/tutorials#27]
[[[[[ C:\Users\matth\simple-todos ]]]]]

=> Started proxy.
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Can't start Mongo server.
MongoDB exited because its port was closed, or was already
taken by a previous instance of MongoDB

Check for other processes listening on port 3001
or other Meteor instances running in the same project.

C:\Users\matth\simple-todos>cd simple-todos
The system cannot find the path specified.

C:\Users\matth\simple-todos>meteor
[[[[[ C:\Users\matth\simple-todos ]]]]]

=> Started proxy.
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Unexpected mongo exit code 48. Restarting.
Can't start Mongo server.
MongoDB exited because its port was closed, or was already
taken by a previous instance of MongoDB

Check for other processes listening on port 3001
or other Meteor instances running in the same project.

C:\Users\matth\simple-todos>

**Comment by electr0sheep** [comment]
Type `localhost:3001` in a browser. If you get a message similar to "It looks like you are trying to access MongoDB over HTTP on the native driver port.", then your error occurs because port 3001 is taken by something else. If not, then it occurs because port 3001 is unable to be occupied by a MongoDB, or possibly anything.

Try running `meteor --port 4000`. The MongoDB seems to occupy the port your client is running on + 1. So if you execute `meteor --port 4000`, the DB will be running on port 4001.

**Comment by lazaridis-com** [comment]
Windows users can use the following command (from withi to get information about the used ports (e.g. `0.0.0.0:3000'). The last column shows the PID, which can be used to identify the task using the port (in the task-manager).

```shell
netstat -ano|find /i "listening"
```

example

```
P:\todo\met>netstat -ano|find /i "listening"
[...]
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       171312
[...]
  TCP    127.0.0.1:3001         0.0.0.0:0              LISTENING       53752
[...]
```

**Comment by lazaridis-com** [comment]
@stubailo @abernix - support question, can be closed.

**Comment by hwillson** [comment]
Agreed @lazaridis-com - thanks - closing!
