### ISSUE TITLE
React: securing delete/check methods for tasks you can't see

### ISSUE THREAD

**Issue by BrianKirwan** [meteor/tutorials#70]
Minor issue with the logic of the React tutorial: in the Publish and Subscribe "Extra method security" section, it's adding "checks to our deleteTask and setChecked methods to make sure only the task owner can delete or check off a private task" - but surely this doesn't make sense as, by this stage, a user who isn't the owner of a private task can't see it, so couldn't delete/check it anyway?

Thanks

**Comment by abernix** [comment]
Even though the ability to delete the task isn't provided in the interface, without adding additional security, it would still be possible for someone to delete another users tasks by calling the Meteor method directly, for example `Meteor.call("deleteTask", ...)`.  It is important to have this security in place, rather than relying on security-by-obscurity. :wink:
