### ISSUE TITLE
React tutorial step 3 is missing 'subscribe'

### ISSUE THREAD

**Issue by mikkelking** [meteor/tutorials#74]
On step 3.4, there is a block of code

```
export default createContainer(() => {
  return {
    tasks: Tasks.find({}).fetch(),
  };
}, App);
```

It should include a _subscribe_ statement, and look like this:

```
export default createContainer(() => {
  Meteor.subscribe('tasks');
  return {
    tasks: Tasks.find({}).fetch(),
  };
}, App);
```

It took me some time to work this out, on the wrong assumption that I was doing something wrong :)
I would have done a PR, but couldn't work out how to do that, as this part is generated, not in the markup.

Keep up the good work!

**Comment by renanlecaro** [comment]
You should still have autopublish at that stage i think, that's why the subscribe is only introduced in step 10.

**Comment by abernix** [comment]
The comment above by @renanlecaro seems correct.

At that stage of the tutorial, publishing happens automatically because of the `autopublish` package which is included with the app creation (i.e. `meteor create ...`) in [step 1](https://github.com/meteor/simple-todos-react/commit/3170e79cfa810c7e91a14440a279e5e2cd053922).

The `autopublish` package is then removed in [step 10.1](https://github.com/meteor/simple-todos-react/commit/f848ec1d44047bc61947c2033f54592abd120f38) and the `Meteor.subscribe` (as you've proposed above) is added in [step 10.3](https://github.com/meteor/simple-todos-react/commit/bdab4ed3dec3368ac6f331b70d8997ccbba85748).

If you were not seeing subscriptions at that stage, I'm truly not sure what happened.  If you anyone runs into this again, please submit a reproduction of your app at that stage (via a GitHub repository, most likely) and we'll be happy to review and address appropriately.
