### ISSUE TITLE
Blaze 9.4 import missing

### ISSUE THREAD

**Issue by crcdng** [meteor/tutorials#79]
In 9.4 

`import { Tasks } from '../api/tasks.js';`

has been removed from `imports/ui/task.js` (compare with 5.3.). The import needs to stay.

**Comment by ontl** [comment]
Can anyone confirm? I noticed this change too, but at first glance app still seems to work without it.

**Comment by lazaridis-com** [comment]
@igames, @ontl 

In section 5.3 of the tutorial, the client accesses the the `Tasks` collection directly.

Section 9 `Removing insecure' disallows this direct access.

In section 9.4, `Meteor` is used to call the methods on the server-side. The `Tasks` is not used directly anymore, and thus the import is not needed.

@hwillson - looks like "invalid" / "worksforme"

**Comment by abernix** [comment]
As stated above by @lazaridis-com, the `Tasks` collection is no longer necessary at this point since it is replaced with a method call therefore removing it is safe.  I've added a bit of text to clarify that this is being done intentionally via this pull request: #118.

Thanks for bringing this up, @i3games!

This issue will close automatically when #118 is merged.
