### ISSUE TITLE
Step 11 (Angular): error trying to run the test

### ISSUE THREAD

**Issue by jasefisher** [meteor/tutorials#92]
After running meteor add practicalmeteor:mocha successfully, when trying to run the test script:

meteor test --driver-package practicalmeteor:mocha

Throws the following error, both before and after setting up all the test scripts (the rest of Step 11).

Error: EPERM: operation not permitted, symlink 'C:\Users\jfisher\AppData\Local\.meteor\packages\meteor-tool\1.4.2_1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\' -> 'C:\Users\jfisher\AppData\Local\Temp\meteor-test-run1ojhdzf\.meteor\local\build\programs\server\node_modules'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at Object.wrapper (C:\tools\fs\files.js:1533:35)
    at Object.files.cp_r (C:\tools\fs\files.js:499:11)
    at C:\tools\fs\files.js:486:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:486:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at C:\tools\fs\files.js:486:13
    at Array.forEach (native)
    at Object.files.cp_r (C:\tools\fs\files.js:475:25)
    at copyDirIntoTestRunnerApp (C:\tools\cli\commands.js:1667:15)
    at doTestCommand (C:\tools\cli\commands.js:1673:5)
    at Command.func (C:\tools\cli\commands.js:1508:10)
    at C:\tools\cli\main.js:1483:23

**Comment by lazaridis-com** [comment]
@jasefisher , looks like a typical permission error. Run your console in Admin mode. See:

https://github.com/nodejs/node-v0.x-archive/issues/6342

@hwillson - should be closable.

**Comment by abernix** [comment]
Contrary to the suggestion above, it's ideal if you do not run Meteor as Administrator – ever.  Generally speaking, it causes problems.

If you are encountering this issue, please first try another test driver (like [`dispatch:mocha`](https://github.com/DispatchMe/meteor-mocha)) and if the problem goes away, open a PR with the `practicalmeteor:mocha` repo. 

If it happens with _both_, then consider opening an issue with Meteor itself (instead of the Tutorials).  It's entirely possible that this cannot be fixed due to Windows' (current) failure to allow unprivileged users the ability to create symlinks.  Junctions are permitted, though they have a number of trade-offs.  Windows Creator Edition (coming later this month) [permits creation of symlinks](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/#bxCWDBx5bFtRGZAI.97) without administrative privileges if Developer Mode enabled.  It's very possible that this Windows update will solve this problem for you if you're able to update to it.
